spring.application.name=campnews


spring.datasource.url=jdbc:mysql:srv-db-dev.mysql.database.azure.com/fairshare
spring.datasource.username=user_fairshare
spring.datasource.password=Welcome$$2026!!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update