spring.application.name=campnews


spring.datasource.url=jdbc:mysql://localhost:3306/campnews
spring.datasource.username=campnews
spring.datasource.password=Camp4News
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update